### ISSUE TITLE
Repository description unclear

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/node-ipfs#14]
I'm not sure what this repo is doing. Can I use any of the stuff here? Can I install and help out? If so, how? 

The top description is also confusing: `ipfs implementation in node https://github.com/jbenet/ipfs`. Does that mean that https://github.com/jbenet/ipfs is a more up-to-date version of this? Or is that just a link to what IPFS is?

**Comment by ralphtheninja** [comment]
@RichardLitt Afaict the link you pointed to is only about the `ipfs` project itself, which in turn is a protocol that can have many implementations of it. The `go-ipfs` project is the canonical project and `node-ipfs` would be a node implementation of the same protocol.

**Comment by RichardLitt** [comment]
Ok, cool. That should be changed, and added to the Readme for this repository. I'll see if I can do this when I get push access from @jbenet.

**Comment by jbenet** [comment]
@richardlitt: make sure to follow the PR model:

make a branch in this same repo, submit as PR and tag someone (ideally
maintainer, in this case @diasdavid) to CR

**Comment by RichardLitt** [comment]
Got it. Just changed the description to point to http://ipfs.io, because that is less ambiguous and can't be done in a PR. Will do a README PR now.

**Comment by diasdavid** [comment]
Didn't this show to you int he Readme? Also added a https://github.com/ipfs/node-ipfs/issues/15 to help with direction

```
node-ipfs
=========

> IPFS Node.js entry point and implementation roadmap

# Description

This repo (will) contains the entry point for the Node.js implementation of IPFS spec, similar to go-ipfs. It also presents the roadmap a modules of node-ipfs and their current state.


# Usage

> Not ready for prime time yet

# Roadmap

- Network
  - [ ] libp2p
    - [ ] Peer Routing
      - [x] kad-routing https://github.com/diasdavid/node-ipfs-kad-router
        - discovery mechanisms
          - [x] mDNS-discovery (https://github.com/diasdavid/node-ipfs-mdns)
          - [ ] random-walk (https://github.com/diasdavid/node-ipfs-random-walk)
          - [x] bootstrap-list (https://github.com/diasdavid/node-ipfs-railing)
      - [ ] mDNS-routing
    - [x] swarm (https://github.com/diasdavid/node-ipfs-swarm)
      - [x] stream muxer (https://github.com/diasdavid/node-spdy-stream-muxer)
      - [x] protocol muxer (https://github.com/diasdavid/node-multistream
      - [x] Identify (https://github.com/diasdavid/node-ipfs-swarm/tree/master/src/identify)
    - [ ] Distributed Record Store
      - [ ] record (needs MerkleDAG node) https://github.com/diasdavid/node-ipfs-record
      - [ ] distributed record store
      - [ ] kad-record-store (implements abstract record store)
      - [ ] abstract-record-store
- Exchange
  - [ ] bitswap
- MerkleDAG
  - [x] MerkleDAG node implementation (needs IPLD)
    - [x] https://github.com/diasdavid/node-ipld
    - [x] MerkleDAGStore https://github.com/diasdavid/node-merkledag-store 
- Spec 
  - https://github.com/ipfs/specs/pull/19
```

**Comment by RichardLitt** [comment]
@diasdavid Made a PR. Should close this issue if merged.

**Comment by RichardLitt** [comment]
Closing as issue is now answered.
