### ISSUE TITLE
Mounting read only /ipfs 

### ISSUE THREAD

**Issue by jbenet** [ipfs/node-ipfs#2]
Read only mounting works now:

in one term:
```sh
mkdir -p foo
echo "bar" > foo/bar
echo "baz" > foo/baz
# foo/baz: added block /XLM1ZETht3wv8vUPXMkx3JZGP5T9txAz782
# foo/bar: added block /XLMCA8WXBNRBwFhzRnHgHFLwGmQzkAQELH7
# foo: added tree /XLNUfxWCtidC125VaSgtM6yM1VRs7PcGvzq
ipfs add -r foo
ipfs mount /ipfs
```

in another:
```sh
# finding files by hash
cat /ipfs/XLMCA8WXBNRBwFhzRnHgHFLwGmQzkAQELH7
# bar
cat /ipfs/XLM1ZETht3wv8vUPXMkx3JZGP5T9txAz782
# baz

# listing directories
ls /ipfs
# ls: ipfs: Permission denied
ls -l /ipfs/XLNUfxWCtidC125VaSgtM6yM1VRs7PcGvzq
# -r--r--r--  0 root  wheel  4 Dec 31  1969 bar
# -r--r--r--  0 root  wheel  4 Dec 31  1969 baz

# path resolution
cat /ipfs/XLNUfxWCtidC125VaSgtM6yM1VRs7PcGvzq/bar
# bar
cat /ipfs/XLNUfxWCtidC125VaSgtM6yM1VRs7PcGvzq/baz
# baz

# symlinks work :)
ln -s /ipfs/XLNUfxWCtidC125VaSgtM6yM1VRs7PcGvzq foo
ls foo
# baz
# bar
cat foo/bar
# bar
```

wow, thanks unix :)  :heart:

## todo

- [ ] service/daemonize
- [ ] listing root shows things available locally
- [ ] leveldb not re-entrant, so ipfs cli should check if a service is running.
- [ ] mount subdirectories. e.g. `ipfs mount <ipfs-path> <os-path>`

**Comment by diasdavid** [comment]
Closing this issue as it referes to the 1st impl of node-ipfs that is no longer supported (as we are building the new one compliant with the spec :) ).
